# Generated by Django 4.0.2 on 2022-12-08 23:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='NDS',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='НДС(у %)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.person', verbose_name='Людина'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.position', verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Заробітня плата'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='position',
            name='count_hours_in_week',
            field=models.PositiveIntegerField(verbose_name='Кількість годин на тиждень'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_position',
            field=models.CharField(max_length=100, verbose_name='Назва посади'),
        ),
    ]
