# Generated by Django 4.0.2 on 2022-12-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_nds_alter_employee_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(verbose_name='Дата народження'),
        ),
    ]
