# Generated by Django 4.0.2 on 2022-12-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_person_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(verbose_name='Дата народження'),
        ),
    ]
